# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db553934bcc5d92d1b0b4de6ac8f44e577c47056af49091fdde2c94e5cad7a9e1cfc700d20c69d220e3de7cbc77287372a9bae90323ca53e3cc1f8b3b72058fb

test:
  secret_key_base: 88adc98e6ad4210dd9cb652e101cfb4898ad6a87d8dfa8a674206a607438131cc7d572dc286948a08b144f5d4ba1b2c4fc7037f8eff0b1e31ffcde130682a424

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
